services:
  - type: web
    name: suncart-manager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
